// com.fric.sirh.notification.enums.NotificationEvent.java

package com.fric.sirh.notification.enums;

public enum NotificationEvent {
    // ==========================================
    // ÉVÉNEMENTS EXISTANTS
    // ==========================================
    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_SUSPENDED,
    EMPLOYEE_REACTIVATED,
    DOCUMENT_UPLOADED,
    COMPANY_CREATED,
    COMPANY_UPDATED,
    COMPANY_DELETED,
    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DEPARTMENT_DELETED,
    POSITION_CREATED,
    POSITION_UPDATED,
    POSITION_DELETED,
    LEAVE_REQUESTED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    LEAVE_CANCELLED,
    LEAVE_BALANCE_GLOBAL_UPDATED,
    LEAVE_BALANCE_INDIVIDUAL_UPDATED,
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    PERMISSION_UPDATED,
    PAYSLIP_UPLOADED,
    SYSTEM,

    // ==========================================
    // ✅ ÉVÉNEMENTS DES CONTRATS
    // ==========================================
    CONTRACT_CREATED,
    CONTRACT_UPDATED,
    CONTRACT_RENEWED,
    CONTRACT_EXPIRED,
    CONTRACT_EXPIRING_SOON,
    CONTRACT_EXPIRING_TWO_WEEKS,
    CONTRACT_EXPIRING_DAILY,
    CONTRACT_EXPIRED_TODAY,
    CONTRACT_ARCHIVED,
    CONTRACT_RESILIATED,
    CONTRACT_EXTENDED,

    // ==========================================
    // ÉVÉNEMENTS DU MODULE DISCIPLINE
    // ==========================================
    DISCIPLINE_EXPLANATION_CREATED,
    DISCIPLINE_EXPLANATION_RESPONDED,
    DISCIPLINE_EXPLANATION_VALIDATED,
    DISCIPLINE_EXPLANATION_REJECTED,
    DISCIPLINE_SANCTION_CREATED,
    DISCIPLINE_SANCTION_LIFTED,
    DISCIPLINE_SANCTION_UPDATED,

    // ==========================================
    // ÉVÉNEMENTS DU MODULE PERFORMANCE
    // ==========================================
    PERFORMANCE_EVALUATION_CREATED,
    PERFORMANCE_EVALUATION_UPDATED,
    PERFORMANCE_EVALUATION_DELETED,
    PERFORMANCE_CRITERE_CREATED,
    PERFORMANCE_CRITERE_UPDATED,
    PERFORMANCE_CRITERE_DELETED
}